# Site settings
author: Michael Ballard
title: A new introduction
header-img: img/home-bg.png
email: ballard.michael9@gmail.com
copyright_name: Michael Ballard
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the blog of Michael A Ballard
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  michaelballard7

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
